export const BACKEND_SERVER_URL =
  process.env.REACT_APP_ENVIRONMENT === "production"
    ? "https://quants.investments:81"
    : process.env.REACT_APP_ENVIRONMENT === "preproduction"
    ? "http://192.168.1.5:8080"
    : "http://localhost:8080";

export const ERROR_CONTACTING_SERVER = "Error contacting server";
export const ERROR_UNEXPECTED_ERROR = "Unexpected error occurred";

export const PERFORMANCE_BOOK_VALUE = 23136;

export const REALTIME_REFRESH_SECS = 5;

export const HOUR_CLOSING = 21; // closing time of the exchange in UTC

export const NUMBER_RESULTS_PER_PAGE = 10;

export const POPUP_TIMEOUT_SECS = 4.5;

export const SCHEDULER_PROCESS_REFRESH_DATA_METRIC_TYPE_OK = 100;
export const SCHEDULER_PROCESS_REFRESH_DATA_METRIC_TYPE_ERROR_DATA_IS_FAULTY = 101;
export const SCHEDULER_PROCESS_REFRESH_DATA_METRIC_TYPE_ERROR_NO_DATA = 102;
export const SCHEDULER_PROCESS_REFRESH_DATA_METRIC_TYPE_ERROR_IS_DISCONTINUOUS = 103;
export const SCHEDULER_PROCESS_REFRESH_DATA_METRIC_TYPE_ERROR_IS_PARTIALLY_LINEAR = 104;
export const SCHEDULER_PROCESS_REFRESH_DATA_METRIC_TYPE_ERROR_NUMBER_ERRORS = 105;
export const SCHEDULER_PROCESS_REFRESH_DATA_METRIC_TYPE_ERROR_DATA_IS_STILL_FRESH = 106;
export const SCHEDULER_PROCESS_REFRESH_DATA_METRIC_TYPE_ERROR_CONVERSION_FOREX = 107;
export const SCHEDULER_PROCESS_RECOMMENDED_SYMBOLS = 2;
export const SCHEDULER_PROCESS_STATE_INVESTMENTS = 3;
export const SCHEDULER_PROCESS_LIST_TRADERS = 4;
export const SCHEDULER_PROCESS_STOCK_NEWS = 5;
